<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Fábrica de Bicicletas</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo ASSETS_PATH; ?>vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?php echo ASSETS_PATH; ?>css/modern-business.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
        <?php $this->loadView("include/navbar"); ?>
    </nav>

	<?php if($isSlider === true): ?>
    <header>
      <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselIndicators" data-slide-to="1"></li>
          <li data-target="#carouselIndicators" data-slide-to="2"></li>
		  <li data-target="#carouselIndicators" data-slide-to="3"></li>
        </ol>
        <?php $this->loadView("include/carousel"); ?>
        <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Anterior</span>
        </a>
        <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Próxima</span>
        </a>
      </div>
    </header>
	<?php endif; ?>

    <!-- Page Content -->
    <div class="container">
        <?php
		/*
		Local separado para carregar todo o layout dentro desse layout pai
		*/
		$this->loadViewInTemplate($viewName, $viewData);
		?>
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; <?php echo NOME_SITE, ' ', date('Y'); ?></p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="<?php echo ASSETS_PATH; ?>vendor/jquery/jquery.min.js"></script>
    <script src="<?php echo ASSETS_PATH; ?>vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>
