		<div class="carousel-inner" role="listbox">
          <!-- Slide One - Set the background image for this slide in the line below -->
          <div class="carousel-item active" style="background-image: url('<?php echo SLIDER_PATH; ?>01.jpg')"><!--//background-image: url('http://placehold.it/1900x1080')\\-->
            <div class="carousel-caption d-none d-md-block">
              <h3>Linha Bicicletas Urbanas</h3>
              <p>Linha custom de bicicletas urbanas especialmente desenvolvidas.</p>
            </div>
          </div>
          <!-- Slide Two - Set the background image for this slide in the line below -->
          <div class="carousel-item" style="background-image: url('<?php echo SLIDER_PATH; ?>02.jpg')">
            <div class="carousel-caption d-none d-md-block">
              <h3>Linha Bicicletas Mata</h3>
              <p>Linha pro de bicicletas de campo desenvolvidas em aço-carbono.</p>
            </div>
          </div>
          <!-- Slide Three - Set the background image for this slide in the line below -->
          <div class="carousel-item" style="background-image: url('<?php echo SLIDER_PATH; ?>03.jpg')">
            <div class="carousel-caption d-none d-md-block">
              <h3>Linha Bicicletas Custom</h3>
              <p>Linha especial desenvolvidas à partir do seu gosto.</p>
            </div>
          </div>
		  <!-- Slide Four - Set the background image for this slide in the line below -->
		  <div class="carousel-item" style="background-image: url('<?php echo SLIDER_PATH; ?>04.jpg')">
            <div class="carousel-caption d-none d-md-block">
              <h3>Linha Bicicletas Top</h3>
              <p>Linha top especial criadas para pessoas especiais.</p>
            </div>
          </div>
        </div>