<div class="container">
    <a class="navbar-brand" href="/">Fábrica de Bicicletas</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/sobrenos">Sobre nós</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/servicos">Serviços</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/nossos-produtos">Nossos produtos</a>
        </li>
		<li class="nav-item">
          <a class="nav-link" href="/contato">Contato</a>
        </li>
      </ul>
    </div>
</div>
<!--
<a class="navbar-brand" href="<?php echo BASE; ?>">EAD TV Digital - Controle de ponto</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarsExampleDefault">
<ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="javascript:void(return false);" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Relatórios</a>
      <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">por funcionário</a>
          <a class="dropdown-item" href="#">por mês</a>
          <a class="dropdown-item" href="#">por período</a>
      </div>
    </li>
</ul>
< !--form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form-- >
</div>
-->